[package]
name = "rust_timer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io="^0.1.8"
rodio="^0.14.0"
home="0.5.3"
